# Dependencies
# - markdown:         redcarpet
highlighter:      rouge

# Permalinks
# - permalink:        pretty
# - relative_permalinks: true

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

title: "Michael J Wilson"
tagline: ""
description: "Follow <a href=\"https://micro.blog/wilsongis\">@wilsongis on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/wilsongis\">@wilsongis on Micro.blog</a>."
baseurl: ""
url: "https://wilson.micro.blog"
markdown: "kramdown"
username: "wilsongis"
microblog_user: "wilsongis"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Michael J Wilson"
name: "Michael J Wilson"
gravatar_hash: "76d30cee972de4789dbf4a8eb4d1a3c2"
avatar: "https://micro.blog/wilsongis/avatar.jpg"
full_name: "Michael J Wilson"
bio: ""
twitter_username: "wilsongis"
github_username: "wilsongis"
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Indiana-Starke"
site_id: "3333"
gems: ["jekyll-paginate"]
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "Michael J Wilson"